### ISSUE TITLE
Nhận xét

### ISSUE THREAD

**Issue by huihui1503** [phineasla-hcmus/3.1-DS-Final#2]
- Mình thấy phần báo cáo của các bạn làm rất đầy đủ và chi tiết.
- Mình thấy mấy bạn có nói là muốn cải tiến mô hình thì theo như mình biết thì một số mô hình recommender system ngoài việc sử dụng các thông tin dạng số (kiểu dạng bảng như trong dữ liệu các bạn phân tích) để tạo embedding representation cho từng thực thể phim thì người ta còn nhúng thêm dữ liệu hình ảnh hoặc văn bản (cái này chắc là để tăng thêm tính semantic cho biểu diễn) - phần dữ liệu này mình thấy các bạn loại bỏ ở phần đầu.

**Comment by cttho** [comment]
Cảm ơn nhận xét của bạn. Minh sẽ tìm hiểu thêm về mô hình mà bạn gợi ý này
